import { withLocalizedSeo } from "@/lib/localized-seo";
import type { Metadata } from "next";
import { ContactForm } from "@/components/ContactForm";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { getSiteContent } from "@/lib/content";
export const metadata: Metadata = withLocalizedSeo({ title: "Building Services & Technical Supervision", description: "Project management, building services supervision, commissioning and handover support from Jyväskylä and Central Finland." }, "/talotekniikka", "en");
export const dynamic = "force-dynamic";
const phases = [{ number: "01", title: "Early planning", items: ["Concept design", "Option studies", "Delivery models", "Cost estimates", "Budgeting", "Contract matters"] }, { number: "02", title: "Implementation", items: ["Selection and management of designers and contractors", "Tendering", "HVAC supervision", "Cost monitoring and reporting", "Authority coordination", "Building services installation supervision"] }, { number: "03", title: "Handover", items: ["Handover and commissioning tasks", "Final financial settlement", "Warranty-period tasks"] }];
export default async function EnglishTechnical() { const content = await getSiteContent(); return <><Header email={content.company.email} locale="en" /><main>
<section className="subhero technical-hero"><div className="shell subhero-grid technical-hero-grid"><div className="technical-hero-copy"><p className="eyebrow">Project management / building services</p><h1>Keep the whole project under control from early planning to handover.</h1><p>JKP Group brings building services project management and supervision together in one clear expert service. The focus is a practical solution, controlled costs and documented delivery.</p><div className="hero-actions technical-hero-actions"><a className="button" href="#enquiry">Discuss your project</a><a className="text-link" href="#phases">View project phases →</a></div></div><div className="technical-image-slot"><img src={content.media.technicalImageUrl || "/images/jkp-teollisuus-hero-asiakkaan-kuva.jpeg"} alt="Building services project management and supervision, example photo" width={1536} height={1022} /></div></div></section>
<section className="process-section" id="phases"><div className="shell"><p className="eyebrow">Project delivery</p><h2>The service covers all project phases from early needs assessment to commissioning and warranty-period tasks.</h2><div className="delivery-phase-grid">{phases.map(p=><article className="delivery-phase" key={p.number}><span>{p.number}</span><h3>{p.title}</h3><ul>{p.items.map(x=><li key={x}>{x}</li>)}</ul></article>)}</div></div></section>
<section className="section supervision-section"><div className="shell section-heading"><div><p className="eyebrow">Supervision</p><h2>Our objective is functional, cost-effective HVAC solutions that are economical to implement and maintain throughout the property's lifecycle.</h2></div><p>The agreed scope may include selection and management of designers and contractors, HVAC installation supervision, commissioning and handover tasks.</p></div><div className="shell" style={{marginTop:28}}><a className="text-link dark-link" href="/en/lvia-valvonta">Explore HVAC supervision →</a></div></section>
<section className="contact-section" id="enquiry"><div className="shell contact-grid"><div><p className="eyebrow">Project enquiry</p><h2>Tell us where your project stands today.</h2><p>A short description of the property, schedule and required responsibility is enough for an initial discussion.</p></div><ContactForm subject="Building services enquiry" locale="en" /></div></section>
</main><Footer content={content} locale="en" /></>; }
