import type { Metadata } from "next";
import { ContactForm } from "@/components/ContactForm";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { getSiteContent } from "@/lib/content";
export const metadata: Metadata = { title: "Building Services & Technical Supervision", description: "Project management, building services supervision, commissioning and handover support from Jyväskylä and Central Finland." };
export const dynamic = "force-dynamic";
const phases = [{ number: "01", title: "Early planning", items: ["Concept design", "Option studies", "Delivery models", "Cost estimates", "Budgeting", "Contract matters"] }, { number: "02", title: "Implementation", items: ["Detailed design", "Tendering", "HVAC and building services supervision", "Cost monitoring and reporting", "Authority coordination", "Technical supervision"] }, { number: "03", title: "Handover", items: ["Handover and delivery tasks", "Final financial settlement", "Warranty-period tasks"] }];
export default async function EnglishTechnical() { const content = await getSiteContent(); return <><Header email={content.company.email} locale="en" /><main>
<section className="subhero technical-hero"><div className="shell subhero-grid technical-hero-grid"><div className="technical-hero-copy"><p className="eyebrow">Project management / building services</p><h1>Keep the whole project under control from early planning to handover.</h1><p>JKP Group brings project management, building services supervision and coordination into one clear expert service. The focus is a practical solution, controlled costs and documented delivery.</p><div className="hero-actions technical-hero-actions"><a className="button" href="#enquiry">Discuss your project</a><a className="text-link" href="#phases">View project phases →</a></div></div><aside className="subhero-code technical-service-index"><div className="technical-index-topline"><span>JKP / TECHNICAL</span><span>01—04</span></div><strong>4</strong><ol>{content.services.map((service, i) => <li key={service.title}><span>{String(i + 1).padStart(2, "0")}</span><b>{["Building services project management", "Technical supervision", "Project management", "Commissioning & handover"][i]}</b></li>)}</ol></aside></div></section>
<section className="section technical-services"><div className="shell section-heading"><div><p className="eyebrow">Services</p><h2>Project management and supervision responsibilities across the lifecycle.</h2></div><p>The service can cover an individual task or continue as an expert responsibility throughout the project.</p></div><div className="shell service-grid">{[["Building services project management","Project coordination from early studies and design through implementation and handover."],["Technical supervision","General, schedule, technical, quality and financial supervision with documentation."],["Project management","Coordination of stakeholders, costs, schedule and decision-making throughout delivery."],["Commissioning & handover","Handover, warranty-period tasks and verification of building systems."]].map(([t,d],i)=><article className="service-card" key={t}><span>{String(i+1).padStart(2,"0")}</span><h3>{t}</h3><p>{d}</p><b>Agreed per project</b></article>)}</div></section>
<section className="process-section" id="phases"><div className="shell"><p className="eyebrow">Project delivery</p><h2>Three phases from need to handover.</h2><div className="delivery-phase-grid">{phases.map(p=><article className="delivery-phase" key={p.number}><span>{p.number}</span><h3>{p.title}</h3><ul>{p.items.map(x=><li key={x}>{x}</li>)}</ul></article>)}</div></div></section>
<section className="section supervision-section"><div className="shell section-heading"><div><p className="eyebrow">Supervision</p><h2>Quality, practicality and documentation made visible on site.</h2></div><p>Supervision covers general, schedule, technical, quality and financial follow-up as well as documentation. Building systems are considered from both implementation and lifecycle perspectives.</p></div><div className="shell" style={{marginTop:28}}><a className="text-link dark-link" href="/en/lvia-valvonta">Explore HVAC supervision →</a></div></section>
<section className="contact-section" id="enquiry"><div className="shell contact-grid"><div><p className="eyebrow">Project enquiry</p><h2>Tell us where your project stands today.</h2><p>A short description of the property, schedule and required responsibility is enough for an initial discussion.</p></div><ContactForm subject="Building services enquiry" locale="en" /></div></section>
</main><Footer content={content} locale="en" /></>; }
